version: '3.1'

services:

  db:
    container_name: image_db
    image: mongo:4.2-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_USER}
      - MONGO_INITDB_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    volumes:
      - ./docker/database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

  redis:
    container_name: image_redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '6379:6379'
    volumes:
      - '/redis_data:/bitnami/redis/data'

  api:
    container_name: image_api
    build:
      context: .
      dockerfile: ./docker/image-service/Dockerfile
    environment:
      NGINX_MAX_UPLOAD: ${MAX_CONTENT_LENGTH}m
    volumes:
    - ./app:/app/app
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/.env
    - ./prestart.sh:/app/prestart.sh
    - ./images:/app/images
    ports:
      - 8081:80
    depends_on:
      - db
      - redis

