version: '3.1'

services:

  database:
    container_name: db
    image: mongo:4.2-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_USER}
      - MONGO_INITDB_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    volumes:
      - ./docker/database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - '/redis_data:/bitnami/redis/data'

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/image-service/Dockerfile
    environment:
      APP_MODULE: app.__init__:app
      LOG_LEVEL: ${GUNICORN_LOG_LEVEL}
    volumes:
    - ./app:/app/app
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/.env
    ports:
      - 80:80
    depends_on:
      - database
      - redis

