# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - 
        name: Create env file
        run: |
          touch .env          
          echo SERVER_NAME=localhost:5000 >> .env
          echo STORAGE_PATH=images >> .env
          echo MONGO_INITDB_ROOT_USERNAME=admin >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=admin >> .env
          echo MONGO_HOST=localhost:27017 >> .env
          echo MONGO_USER=noadmin >> .env
          echo MONGO_PASS=noadmin >> .env
          echo MONGO_DBNAME=images >> .env
          echo GUNICORN_LOG_LEVEL=debug >> .env
          echo MAX_CONTENT_LENGTH=16 >> .env
          echo REDIS_HOST=localhost:6379 >> .env
          cat .env
 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/image-service/Dockerfile
          push: false
